[package]
name = "web-mvc"
version = "0.1.0"
authors = ["Julian Goldsmith <julian@juliangoldsmith.com>"]

[dependencies]
serde = "1"
serde_json = "1"
serde_derive = "1"
stdweb = { path = "../stdweb/" }
